"""
Django settings for traktordetal project.

Generated by 'django-admin startproject' using Django 4.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(PROJECT_DIR)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/



# Application definition

INSTALLED_APPS = [
    "seo",
    "home",
    "aboutindex",
    "search",
    "advertisement",
    "robots",

#    "advertisement.apps.AdvertisementConfig",
    "core",
    "services",
    "usefull",
#    "usefull.apps.UsefullConfig",
    "currency",
    "contact_us",
    "feedback",
    "employee",    
    "drf_yasg",
    "wagtailcache",
    "crispy_forms",
    "crispy_tailwind",
    'wagtailsvg',
    'wagtail.contrib.modeladmin',
    "wagtail_localize",
    "wagtailvideos",
    "generic_chooser",
    "wagtail_localize.locales",
    "wagtail_localize.modeladmin",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    'wagtail.contrib.styleguide',
    'wagtail.contrib.settings',
    "wagtail.embeds",
    "wagtail.sites",
    'wagtail.contrib.sitemaps',
    'django.contrib.sitemaps',
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail_color_panel",
    "corsheaders",

    "wagtail.admin",
    "wagtail",
    "wagtail.api.v2",
    "tailwind",
    "wagtailmetadata",
    "modelcluster",
    "taggit",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_browser_reload",
    "debug_toolbar",
    "django_filters",
    "rest_framework",
    "rest_framework_recaptcha",
    "colorfield",
    "wagtail.contrib.frontend_cache",
    "ckeditor",
    "phonenumber_field",
    "storages",


]



SITE_ID = 1
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"

WAGTAILMETADATA_IMAGE_FILTER = "fill-688x272|format-png"


CRISPY_TEMPLATE_PACK = "tailwind"

WAGTAILSVG_UPLOAD_FOLDER = 'svg'

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",

    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "wagtailcache.cache.UpdateCacheMiddleware",
    'wagtailcache.cache.FetchFromCacheMiddleware',

]

ROOT_URLCONF = "wellhouse.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "wellhouse.wsgi.application"





# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

WAGTAIL_I18N_ENABLED = True

USE_TZ = True

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [

    ("tr", "Turkish"),
    ("en", "English"),
    ("ru", "Русский"),
    ("de", "german"),
]

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale/"),

]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

# ManifestStaticFilesStorage is recommended in production, to prevent outdated
# JavaScript / CSS assets being served from cache (e.g. after a Wagtail upgrade).
# See https://docs.djangoproject.com/en/4.1/ref/contrib/staticfiles/#manifeststaticfilesstorage
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"


STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = "/media/"

# DEBUG TOOLBAR internal ip
INTERNAL_IPS = [
    "127.0.0.1",
]

# Wagtail settings

WAGTAIL_SITE_NAME = "wellhouse"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "localhost"

CORS_ORIGIN_ALLOW_ALL = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'noreply@traktordetal.com'
EMAIL_HOST_PASSWORD = 'JdDz9bxPCdsqEqua8fSV'
DEFAULT_FROM_EMAIL = 'noreply@traktordetal.com'


#DEFAULT_FROM_EMAIL = 'salmanalakbarzade@demodev.click'
#EMAIL_HOST_USER = 'zekiyev014@gmail.com'

